# Generated by Django 2.2.16 on 2021-12-12 07:59

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[reviews.validators.year_validator], verbose_name='Год выпуска'),
        ),
    ]
